#Note that sfladmin needs to run on the host, not in a docker container, as it runs some shell scripts
#That makes this docker compose redundant, but left here for testing purposes.
version: "3.7"
services:
  sflogadmin:
    container_name: sflogadmin
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '6060:6060'
